import { Film } from "@/app/types";

export const FILMS: Film[] = [
  {
    id: "kung-fu-panda",
    title: "Kung Fu Panda",
    originalTitle: "Kung Fu Panda",
    director: "Mark Osborne, John Stevenson",
    year: 2008,
    duration: "92 min",
    genre: ["Animazione", "Commedia", "Avventura"],
    date: "Martedì 14 Luglio",
    time: "21:30",
    plot: "Il panda Po, un pigro e imbranato cameriere, viene inaspettatamente scelto per compiere un'antica profezia e diventare il leggendario Guerriero Dragone per difendere la Valle della Pace.",
    cast: ["Jack Black", "Dustin Hoffman", "Angelina Jolie", "Jackie Chan"],
    rating: 5,
    imageColor: "#E23E28",
    illustrationType: "reel",
    imagePath: "/images/kung-fu-panda.jpg"
  },
  {
    id: "ce-ancora-domani",
    title: "C'è ancora domani",
    originalTitle: "C'è ancora domani",
    director: "Paola Cortellesi",
    year: 2023,
    duration: "118 min",
    genre: ["Drammatico", "Commedia"],
    date: "Martedì 21 Luglio",
    time: "21:30",
    plot: "Nella Roma del secondo dopoguerra, Delia cerca di farsi strada tra le fatiche quotidiane, un marito violento e il desiderio di un futuro migliore e indipendente per sua figlia.",
    cast: ["Paola Cortellesi", "Valerio Mastandrea", "Romana Maggiora Vergano", "Emanuela Fanelli"],
    rating: 5,
    imageColor: "#262626",
    illustrationType: "vintage",
    imagePath: "/images/ce-ancora-domani.jpg"
  },
  {
    id: "wonka",
    title: "Wonka",
    originalTitle: "Wonka",
    director: "Paul King",
    year: 2023,
    duration: "116 min",
    genre: ["Fantastico", "Musicale", "Avventura"],
    date: "Martedì 28 Luglio",
    time: "21:30",
    plot: "Le origini del giovane Willy Wonka e la fantastica storia di come sia diventato il più grande inventore, mago e cioccolatiere del mondo prima di aprire la sua famosa fabbrica.",
    cast: ["Timothée Chalamet", "Calah Lane", "Keegan-Michael Key", "Hugh Grant"],
    rating: 4,
    imageColor: "#E23E28",
    illustrationType: "stars",
    imagePath: "/images/wonka.jpg"
  },
  {
    id: "the-menu",
    title: "The Menu",
    originalTitle: "The Menu",
    director: "Mark Mylod",
    year: 2022,
    duration: "107 min",
    genre: ["Thriller", "Commedia Nera"],
    date: "Martedì 4 Agosto",
    time: "21:30",
    plot: "Una giovane coppia viaggia verso un'isola esclusiva per mangiare in un ristorante di lusso, ma lo chef ha preparato un menù inquietante, con alcune mortali sorprese per i suoi abbienti ospiti.",
    cast: ["Anya Taylor-Joy", "Nicholas Hoult", "Ralph Fiennes"],
    rating: 4,
    imageColor: "#1A1A1A",
    illustrationType: "scelte",
    imagePath: "/images/the-menu.jpg"
  },
  {
    id: "qualunquemente",
    title: "Qualunquemente",
    originalTitle: "Qualunquemente",
    director: "Giulio Manfredonia",
    year: 2011,
    duration: "96 min",
    genre: ["Commedia"],
    date: "Martedì 25 Agosto",
    time: "21:30",
    plot: "Cetto La Qualunque, un politico locale profondamente corrotto, torna in Italia dopo un periodo di latitanza per candidarsi a sindaco e difendere le sue proprietà (e il suo stile di vita) dalla minaccia della legalità.",
    cast: ["Antonio Albanese", "Sergio Rubini", "Lorenza Indovina", "Nicola Rignanese"],
    rating: 4,
    imageColor: "#E23E28",
    illustrationType: "spotlight",
    imagePath: "/images/qualunquemente.jpg"
  },
  {
    id: "coco",
    title: "Coco",
    originalTitle: "Coco",
    director: "Lee Unkrich",
    year: 2017,
    duration: "105 min",
    genre: ["Animazione", "Musicale", "Avventura"],
    date: "Martedì 1 Settembre",
    time: "21:30",
    plot: "Il giovane Miguel, che sogna di diventare un musicista nonostante il veto della sua famiglia, intraprende un viaggio straordinario nella variopinta Terra dei Morti per scoprire la sua vera storia.",
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt"],
    rating: 5,
    imageColor: "#262626",
    illustrationType: "romance",
    imagePath: "/images/coco.jpg"
  },
  {
    id: "una-notte-al-museo",
    title: "Una notte al museo",
    originalTitle: "Night at the Museum",
    director: "Shawn Levy",
    year: 2006,
    duration: "108 min",
    genre: ["Commedia", "Avventura", "Fantastico"],
    date: "Martedì 8 Settembre",
    time: "21:30",
    plot: "Larry Daley, un padre sfortunato, accetta un lavoro come guardiano notturno al Museo di Storia Naturale. Presto scopre che, grazie a un'antica maledizione egizia, di notte le esposizioni prendono letteralmente vita.",
    cast: ["Ben Stiller", "Carla Gugino", "Dick Van Dyke", "Robin Williams"],
    rating: 4,
    imageColor: "#1A1A1A",
    illustrationType: "camera",
    imagePath: "/images/una-notte-al-museo.jpg"

  },
  {
    id: "luomo-del-labirinto",
    title: "L'uomo del labirinto",
    originalTitle: "L'uomo del labirinto",
    director: "Donato Carrisi",
    year: 2019,
    duration: "130 min",
    genre: ["Thriller", "Mistero"],
    date: "Martedì 15 Settembre",
    time: "21:30",
    plot: "Samantha si risveglia in ospedale senza memoria, dopo essere stata rapita e tenuta prigioniera in un labirinto per quindici anni. Un profiler e un investigatore privato cercano di ricostruire la sua storia per catturare il mostro.",
    cast: ["Toni Servillo", "Dustin Hoffman", "Valentina Bellè"],
    rating: 4,
    imageColor: "#262626",
    illustrationType: "clapper",
    imagePath: "/images/luomo-del-labirinto.jpg"

  },
  {
    id: "alla-ricerca-di-nemo",
    title: "Alla ricerca di Nemo",
    originalTitle: "Finding Nemo",
    director: "Andrew Stanton",
    year: 2003,
    duration: "100 min",
    genre: ["Animazione", "Avventura", "Commedia"],
    date: "Martedì 22 Settembre",
    time: "21:30",
    plot: "Marlin, un pesce pagliaccio eccessivamente protettivo, intraprende un lungo e pericoloso viaggio attraverso l'intero oceano assieme alla smemorata Dory per ritrovare suo figlio Nemo, catturato da un subacqueo.",
    cast: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe"],
    rating: 5,
    imageColor: "#E23E28",
    illustrationType: "reel",
    imagePath: "/images/nemo.jpg"


  },
  {
    id: "perfetti-sconosciuti",
    title: "Perfetti Sconosciuti",
    originalTitle: "Perfetti Sconosciuti",
    director: "Paolo Genovese",
    year: 2016,
    duration: "97 min",
    genre: ["Commedia", "Drammatico"],
    date: "Martedì 29 Settembre",
    time: "21:30",
    plot: "Durante una cena tra amici storici, la padrona di casa propone un gioco rischioso: mettere tutti i propri smartphone sul tavolo e condividere pubblicamente ogni telefonata, sms o notifica in arrivo. Quello che comincia come un esperimento divertente si trasforma rapidamente in un implacabile disvelamento di ipocrisie e segreti.",
    cast: ["Marco Giallini", "Kasia Smutniak", "Valerio Mastandrea", "Anna Foglietta", "Giuseppe Battiston"],
    rating: 4,
    imageColor: "#1A1A1A",
    illustrationType: "clapper",
    imagePath: "/images/perfetti-sconosciuti.jpg"
  }
];